"""Crear tabla Actividades

Revision ID: 3f72b16fd026
Revises: 
Create Date: 2024-11-14 10:04:17.781174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f72b16fd026'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('año_minimo', sa.Integer(), nullable=False),
    sa.Column('año_maximo', sa.Integer(), nullable=False),
    sa.CheckConstraint('año_maximo > año_minimo', name='check_año_maximo_mayor_año_minimo'),
    sa.CheckConstraint('año_minimo > 0 AND año_maximo > 0', name='check_años_positivos'),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_hora_fin_mayor_hora_inicio'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades')
    # ### end Alembic commands ###
